### ISSUE TITLE
Why so many deployment requests?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/app-manager#36]
All from a single PR, with no further changes:

![screen shot 2015-09-23 at 17 27 13](https://cloud.githubusercontent.com/assets/57483/10051214/5f848288-6218-11e5-92a9-86afd734baa6.png)

**Comment by chrismytton** [comment]
Heroku are currently having [issues with their API](https://status.heroku.com/incidents/813) so it's possible this is a transient issue related to that.

**Comment by tmtmtmtm** [comment]
Yep — I think this must have been that. Either way it resolved itself! :)
